---
- hosts: ralexandrov
  vars_prompt:
    - name: editor
      private: false

  environment:
    EDITOR: "{{ editor }}"

  tasks:
    - name: Change default editor.
      lineinfile:
        dest: /etc/profile.d/px-editor.sh
        regexp: "^EDITOR"
        line: "EDITOR={{ editor }}"
        create: true
        mode: 0644
