---
- name: Base Packages RHEL7|8/Debian/Ubuntu
  hosts: vps

  vars:
      rhel: [ 'nano', 'vim', 'nmap', 'nmap-ncat', 'net-tools', 'htop', 'rsync', 'mc', 'tar', 'unzip', 'git', 'sudo', 'epel-release' ]
      debian: [ 'nano', 'vim', 'nmap', 'net-tools', 'htop', 'rsync', 'mc', 'tar', 'unzip', 'git', 'sudo' ]

  tasks:

      - name: Debug
        debug: msg={{ ansible_os_family }}

      - name: Install Base Packages on RHEL7|8
        yum:
          name: '{{ rhel }}'
          state: latest
        when: ansible_os_family == "RedHat"

      - name: Install Base Packages on Debian|Ubuntu
        apt:
          name: '{{ debian }}'
          state: latest
        when: ansible_os_family == "Debian"
