---
- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_distribution }}

- hosts: os_CentOS
  gather_facts: false
  tasks:
    - name: Ping
      ping:

- hosts: os_Ubuntu
  gather_facts: false
  tasks:
    - name: Install inxi
      apt:
        name: inxi
        state: latest

- hosts: os_Archlinux
  gather_facts: false
  tasks:
    - name: Install screenfetch
      pacman:
        name: screenfetch
        state: present
