---
- hosts: all
  tasks:
  - name: Debug
    debug: msg={{ ansible_os_family }}

  - set_fact: package_name=httpd
    when: ansible_os_family == "RedHat"

  - set_fact: package_name=apache2
    when: ansible_os_family == "Debian"

  - name: Install httpd package
    yum: name={{ package_name }} state=latest
    when: ansible_os_family == "RedHat"

  - name: Install apache2 package
    apt: name={{ package_name }} state=latest
    when: ansible_os_family == "Debian"
