---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: target_host
      prompt: Please enter the target host or group
      private: false
  tasks:
    - add_host:
        name: "{{ item }}"
        groups: dynamically_created_hosts
      with_items: "{{ target_host.split(',') }}"

- hosts: dynamically_created_hosts
  tasks:
    - name: Install packages
      portage: package={{ item }} state=latest
      with_items:
        - portage
        - gentoolkit
        - genlop
