---
# Change the hosts field with host you'd like.
# Be carriful with yaml syntax max line length is 80
# For multiple hosts add on new lines, same like users: field for example.
- hosts: all

  gather_facts: false

  vars:
    users:
      - venzi
      - iyovchev
    sysadmins:
      - rmarinchev
      - joro

  tasks:
    - name: Create devops group
      group:
        name: devops
        state: present

    - name: Create sysadmins group
      group:
        name: sysadmins
        state: present

    - name: Create devops accounts
      user:
        name: "{{ item }}"
        groups: devops
      with_items: "{{ users }}"

    - name: Create devops account ralexandrov with zsh
      user:
        name: ralexandrov
        groups: devops
        shell: /bin/zsh

    - name: Create sysadmins accounts
      user:
        name: "{{ item }}"
        groups: sysadmins
      with_items: "{{ sysadmins }}"

    - name: Add authorized key for rmarinchev
      authorized_key:
        user: rmarinchev
        state: present
        key: "{{ lookup('file', 'rmarinchev-devops.pub') }}"

    - name: Add authorized key for joro
      authorized_key:
        user: joro
        state: present
        key: "{{ lookup('file', 'joro-devops.pub') }}"

    - name: Add authorized key for ralexandrov
      authorized_key:
        user: ralexandrov
        state: present
        key: "{{ lookup('file', 'rosen-devops.pub') }}"

    - name: Add authorized key for root
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'root.pub') }}"

    - name: Add authorized key for venzi
      authorized_key:
        user: venzi
        state: present
        key: "{{ lookup('file', 'ventsi-devops.pub') }}"

    - name: Add authorized key for iyovchev
      authorized_key:
        user: iyovchev
        state: present
        key: "{{ lookup('file', 'iyovchev-devops.pub') }}"

    - name: Allow devops users to sudo without a password
      lineinfile:
        dest: /etc/sudoers.d/devops
        regexp: "^%devops"
        line: "%devops ALL=(ALL) NOPASSWD: ALL, !/bin/su, !/usr/bin/chattr"
        create: true
        mode: 0600
        validate: /usr/sbin/visudo -cf %s

    - name: Allow sysadmins users to sudo without a password
      lineinfile:
        dest: /etc/sudoers.d/sysadmins
        regexp: "^%sysadmins"
        line: "%sysadmins ALL=(ALL)NOPASSWD:ALL"
        create: true
        mode: 0600
        validate: /usr/sbin/visudo -cf %s

    - name: Protect /etc/sudoers
      file:
        path: /etc/sudoers
        attr: -ai

    - name: Protect /etc/sudoers.d/devops
      file:
        path: /etc/sudoers.d/devops
        attr: +ai

    - name: Protect /etc/sudoers.d/sysadmins
      file:
        path: /etc/sudoers.d/sysadmins
        attr: +ai
